### ISSUE TITLE
OP_REQUIRES failed at conv_ops.cc:977 : Not found: No algorithm worked!

### ISSUE THREAD

**Issue by XiongWei1012** [fabiotosi92/LGC-Tensorflow#2]
[*] Start Testing...
2020-08-18 02:38:44.040759: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
 [*] Test image:b'./images/disparity/ad-census/000043_10_LR.png'
2020-08-18 02:38:44.199417: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-08-18 02:38:45.134762: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at conv_ops.cc:977 : Not found: No algorithm worked!
2020-08-18 02:38:45.153162: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at conv_ops.cc:977 : Not found: No algorithm worked!
2020-08-18 02:38:45.167871: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at conv_ops.cc:977 : Not found: No algorithm worked!
2020-08-18 02:38:45.531216: W tensorflow/core/kernels/queue_base.cc:277] _0_input_producer: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
         [[{{node LFN/disparity/conv1/conv/Conv2D}}]]
         [[Pad_2/_261]]
  (1) Not found: No algorithm worked!
         [[{{node LFN/disparity/conv1/conv/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./model/main.py", line 61, in <module>
    tf.app.run()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./model/main.py", line 57, in main
    model.test(args)
  File "/home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/model.py", line 569, in test
    confidence = self.sess.run(prediction, feed_dict={self.left: val_left, self.disp: val_disp})
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
         [[node LFN/disparity/conv1/conv/Conv2D (defined at /home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/ops.py:10) ]]
         [[Pad_2/_261]]
  (1) Not found: No algorithm worked!
         [[node LFN/disparity/conv1/conv/Conv2D (defined at /home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/ops.py:10) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node LFN/disparity/conv1/conv/Conv2D:
 Pad (defined at /home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/model.py:132)
 LFN/disparity/conv1/weights/read (defined at /home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/ops.py:6)

Input Source operations connected to node LFN/disparity/conv1/conv/Conv2D:
 Pad (defined at /home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/model.py:132)
 LFN/disparity/conv1/weights/read (defined at /home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/ops.py:6)

Original stack trace for 'LFN/disparity/conv1/conv/Conv2D':
  File "./model/main.py", line 61, in <module>
    tf.app.run()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./model/main.py", line 51, in main
    dataset=args.dataset
  File "/home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/model.py", line 41, in __init__
    self.build_model()
  File "/home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/model.py", line 77, in build_model
    'LGC': self.LGC}[self.model]()
  File "/home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/model.py", line 185, in LGC
    self.LFN() if self.late_fusion else self.EFN()
  File "/home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/model.py", line 141, in LFN
    conv1_disp = ops.conv2d(model_input_disp, [kernel_size, kernel_size, 1, filters], 1, True, padding='VALID')
  File "/home/notebook/data/group/xiongwei_80240510/LGC-Tensorflow-master/model/ops.py", line 10, in conv2d
    x = tf.nn.conv2d(x, W, strides=[1, strides, strides, 1], padding=padding)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by XiongWei1012** [comment]
Dear sir, thanks for your works.
When I test your code with my disparity, I got the error:
**my command**:  python ./model/main.py --is_training False --batch_size 1 --dataset ./utils/my_kitti_testing_set.txt  --checkpoint_path ./checkpoint/ConfNet/AD-CENSUS/model ./checkpoint/LFN/AD-CENSUS/model ./checkpoint/LGC/CCNN/AD-CENSUS/model --output_path ./output/ --model LGC --late_fusion
**my disparity and left image is 3 channels**
**my_kitti_testing_set.txt** 
./images/disparity/ad-census/000043_10_LR.png;./images/colored_0/000043_10.png

**I save the disparity as 3 channels because i find the other error "input and filter must have the same depth: 1 vs 3"**

**Comment by XiongWei1012** [comment]
**my_kitti_testing_set.txt** 
./images/disparity/ad-census/000043_10_LR.png;./images/colored_0/000043_10.png
